// Generated by CoffeeScript 1.9.3
(function() {
  var pm2;

  pm2 = require('pm2');

  pm2.connect(function() {
    return pm2.start({
      script: 'app.js',
      exec_mode: 'cluster',
      instances: 4,
      max_memory_restart: '100M'
    }, function(err, apps) {
      return pm2.disconnect();
    });
  });

}).call(this);
