// Generated by CoffeeScript 1.9.3
(function() {
  var express, passport, router;

  express = require("express");

  passport = require("passport");

  router = express.Router();

  router.post('/login', passport.authenticate('local', {
    failureRedirect: '/login'
  }), function(req, res) {
    return res.redirect('/');
  });

  router.get('/facebook', passport.authenticate('facebook', {
    scope: ['email']
  }));

  router.get('/facebook/callback', passport.authenticate('facebook', {
    failureRedirect: '/'
  }), function(req, res) {
    return res.redirect('/media');
  });

  router.get('/google', passport.authenticate('google', {
    scope: ['https://www.googleapis.com/auth/plus.login', 'https://www.googleapis.com/auth/plus.profile.emails.read']
  }));

  router.get('/google/callback', passport.authenticate('google', {
    failureRedirect: '/'
  }), function(req, res) {
    return res.redirect('/media');
  });

  router.get('/twitter', passport.authenticate('twitter'));

  router.get('/twitter/callback', passport.authenticate('twitter', {
    failureRedirect: '/'
  }), function(req, res) {
    return res.redirect('/media');
  });

  module.exports = router;

}).call(this);
